### ISSUE TITLE
PostgreSQL's LIKE is case sensitive

### ISSUE THREAD

**Issue by kvdnberg** [SamsonIT/AutocompleteBundle#16]
The LIKE function in PostgreSQL is unfortunately case sensitive, while other SQL systems are case insensitive with LIKE. 

To get consistent behavior I would suggest the following change:

Query\ResultsFetcher.php, line 66
```php
                $expressions[] = $qb->expr()->like('LOWER(' . $field . ')', ':query' . $key . $key2);
                $qb->setParameter('query' . $key . $key2, '%' . strtolower($searchWord) . '%');
```

**Comment by ErikTrapman** [comment]
Thanks for the issue, it's been a while, but i've changed it in https://github.com/SamsonIT/AutocompleteBundle/commit/2f0a3204162ef4c95b0ff280d4d4eb5b72970bdf
